### ISSUE TITLE
App crashes when hitting "Rate this business" button.

### ISSUE THREAD

**Issue by tuanho98** [nehadil/CovidFight#48]
When you click the button on businesses that were reviewed, it crashed. 
But when I click it on business that was never reviewed its fine. Then I reviewed it, then it crashes when I came back to hit the button.

**Comment by charliedil** [comment]
The problem was in the ReviewItem class. To pull data from the database in into a ReviewItem object, the ReviewItem class has to have a no argument constructor. Somehow this was deleted in your branch. Pull from my branch for the fix.

![image](https://user-images.githubusercontent.com/40442056/97732343-c9f66f80-1aac-11eb-8609-a96c77ddcc32.png)
